apiVersion: v1

kind: Service

metadata:
  name: story-service

spec:
  selector:
    app: story-app
  type: LoadBalancer
  ports:
    - protocol: 'TCP'
      port: 5000
      targetPort: 5000

---

apiVersion: apps/v1

kind: Deployment

metadata:
  name: story-deploy

spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-app
  template:
    metadata:
      labels:
        app: story-app
    spec:
      containers:
        - name: story-app
          image: dommort/api-data:1
          # set path of data in container
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      # set a volume
      volumes:
        - name: story-volume
          # set volume type
          # emptyDir and set {} so no config; survives restarts, but no pod removal
          emptyDir: {}