# to run this, just use:
# docker compose up -d
# specify the version of file format
version: '3.8'

# add containers
# no need of network since docker-compose creates a new env
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password    # solve auth problem
    volumes:
      - datamysql:/var/lib/mysql
    env_file:
      - .env
  
  apiapp:
    build: ./                       # image with specific Dockerfile build
    image: apiapp:network           # set name
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - mysql

# set volumes
volumes:
  datamysql:
  .: